apiVersion: v1
kind: Pod
metadata:
  name: yellow
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4500"
    image: busybox
    name: lemon
  - command:
    - sleep
    - "4500"
    image: redis
    name: gold
